---

- name: nvidia-modprobe is installed
  apt:
    name: nvidia-modprobe
    state: present
    update_cache: yes

- name: nvidia-docker is installed
  apt:
    deb: '{{ nvidia_docker_deb_url }}'
    state: present
